services:
  mysql.host:
    ports:
      - $SQL_HOST_PORT:3306
    image: "mysql:8.0.22"
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_USER: $SQL_USER
      MYSQL_PASSWORD: $SQL_PASS
      MYSQL_ROOT_PASSWORD: $SQL_ROOT_PASS
      MYSQL_DATABASE: $SQL_DB
    command: "mysqld --default-authentication-plugin=mysql_native_password"
